/*
 * Car Workshop
 *
 * <h2> WILL BE UPDATED!</h2></br><b>Incomplete</b> API for car workshop system (lacks employees and parts management).</br><a href=\"https://app.swaggerhub.com/apis/soft_eng/project/0.1.1\">Swagger project (contains models)</a>.
 *
 * OpenAPI spec version: 0.1.1
 * Contact: k.baciejowski@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using se_project.Attributes;
using se_project.Functions;
using se_project.Models;
using Swashbuckle.AspNetCore.Annotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace se_project.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class VisitsApiController : ControllerBase
    {
        private readonly CompanyDBEntities _context;

        public VisitsApiController(CompanyDBEntities context)
        {
            _context = context;
        }

        /// <summary>
        /// Schedule a visit
        /// </summary>
        /// <param name="body">Information about scheduled visit. Required actions can be modified later on by an employee.</param>
        /// <response code="400">Validation exception</response>
        [HttpPost]
        [Route("/api/0.1.1/visits")]
        [ValidateModelState]
        [SwaggerOperation("AddVisit")]
        public virtual IActionResult AddVisit([FromBody] Body3 body)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }

            var car = _context.Cars.FirstOrDefault(x => x.LicensePlate.Equals(body.LicensePlate));
            if (car is null)
            {
                return StatusCode(404);
            }

            var client = _context.Users.FirstOrDefault(x => x.Username == car.Username);
            if (client is null)
            {
                return StatusCode(400);
            }

            var employees = _context.Users
                .Include(x => x.AssignedVisits);
            var min = employees.Where(x => x.UserType == UserType.WORKSHOP_EMPLOYEE)
                .Min(x => x.AssignedVisits.Count);
            var employee = employees.FirstOrDefault(x =>
                x.AssignedVisits.Count == min && x.UserType == UserType.WORKSHOP_EMPLOYEE);
            if (employee is null)
            {
                return StatusCode(400);
            }

            var visit = new Visit
            {
                Date = body.Date,
                Car = car,
                LicensePlate = body.LicensePlate,
                RequiredActions = body.RequiredActions,
                Type = body.Type,
                Priority = body.Priority,
                Status = 0,
                CarOwnerUsername = client.Username,
            };

            var ev = new EmployeeVisit
            {
                VisitId = _context.Visits.Max(x => x.VisitId) + 1,
                Username = employee.Username
            };

            _context.Visits.Add(visit);
            _context.EmployeesVisits.Add(ev);
            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(400);
            }

            return new ObjectResult(visit);
        }

        [HttpGet]
        [Route("/api/0.1.1/visits")]
        [ValidateModelState]
        [SwaggerOperation("GetVisits")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Visit>), description: "Successful operation")]
        public virtual IActionResult GetVisits()
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }

            List<Visit> visits;
            if (sender.Item2 == UserType.CLIENT)
            {
                visits = _context.Visits.Where(x => x.CarOwnerUsername.Equals(sender.Item1)).ToList();
            }
            else if (sender.Item2 == UserType.WORKSHOP_EMPLOYEE)
            {
                var visitIds = _context.EmployeesVisits
                    //.Include(x => x.Visit)
                    //todo fix relation and use include
                    .Where(x => x.Username.Equals(sender.Item1))
                    .Select(x => x.VisitId).ToList();

                visits = _context.Visits.Where(x => visitIds.Contains(x.VisitId)).ToList();
            }
            else
            {
                return StatusCode(403);
            }

            return new ObjectResult(visits);
        }

        /// <summary>
        /// Find visits by Status
        /// </summary>
        /// <remarks>Multiple status values can be provided with comma separated strings</remarks>
        /// <param name="status">Status values that need to be considered for filter</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid status value</response>
        [HttpGet]
        [Route("/api/0.1.1/visits/find_by_status")]
        [ValidateModelState]
        [SwaggerOperation("FindVisits")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<InlineResponse200>), description: "Successful operation")]
        public virtual IActionResult FindVisits([FromQuery][Required()] List<string> status)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }

            if (status.Count < 1)
            {
                return new ObjectResult(_context.Visits);
            }

            var visits = _context.Visits.Where(x => status.Contains(((Visit.StatusEnum)x.Status).ToString()));

            return new ObjectResult(visits);
        }

        /// <summary>
        /// Find visit by Id
        /// </summary>

        /// <param name="visitId"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid id supplied</response>
        /// <response code="404">Visit not found</response>
        [HttpGet]
        [Route("/api/0.1.1/visits/{visitId}")]
        [ValidateModelState]
        [SwaggerOperation("GetVisit")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<InlineResponse200>), description: "Successful operation")]
        public virtual IActionResult GetVisit([FromRoute][Required] int? visitId)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }

            if (visitId < 0)
            {
                return StatusCode(400);
            }

            var visit = _context.Visits.FirstOrDefault(x => x.VisitId.Equals(visitId));
            if (visit is null)
            {
                return StatusCode(404);
            }

            return new ObjectResult(visit);
        }

        /// <summary>
        /// Marks diagnostic as finished
        /// </summary>

        /// <param name="visitId"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid visit id supplied</response>
        /// <response code="404">Visit not found</response>
        [HttpPut]
        [Route("/api/0.1.1/visits/{visitId}/diagnose")]
        [ValidateModelState]
        [SwaggerOperation("Diagnose")]
        public virtual IActionResult Diagnose([FromRoute][Required] int? visitId)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }
            // if (sender.Item2 != UserType.WORKSHOP_EMPLOYEE)
            //     return StatusCode(403);

            var visit = _context.Visits.FirstOrDefault(x => x.VisitId.Equals(visitId));
            if (visit is null)
            {
                return StatusCode(404);
            }

            visit.Status = Visit.StatusEnum.CheckedInEnum;

            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(400);
            }

            return new ObjectResult(visit);
        }

        /// <summary>
        /// Marks maintenance as finished
        /// </summary>

        /// <param name="visitId"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid visit id supplied</response>
        /// <response code="404">Visit not found</response>
        [HttpPut]
        [Route("/api/0.1.1/visits/{visitId}/maintain")]
        [ValidateModelState]
        [SwaggerOperation("Maintain")]
        public virtual IActionResult Maintain([FromRoute][Required] int? visitId)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }

            // if (sender.Item2 != UserType.WORKSHOP_EMPLOYEE)
            //     return StatusCode(403);

            var visit = _context.Visits.FirstOrDefault(x => x.VisitId.Equals(visitId));
            if (visit is null)
            {
                return StatusCode(404);
            }

            visit.Status = Visit.StatusEnum.AtServiceEnum;

            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(400);
            }

            return new ObjectResult(visit);
        }

        /// <summary>
        /// Marks repairment as finished
        /// </summary>

        /// <param name="visitId"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid visit id supplied</response>
        /// <response code="404">Visit not found</response>
        [HttpPut]
        [Route("/api/0.1.1/visits/{visitId}/repair")]
        [ValidateModelState]
        [SwaggerOperation("Repair")]
        public virtual IActionResult Repair([FromRoute][Required] int? visitId)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }

            // if (sender.Item2 != UserType.WORKSHOP_EMPLOYEE)
            //     return StatusCode(403);

            var visit = _context.Visits.FirstOrDefault(x => x.VisitId.Equals(visitId));
            if (visit is null)
            {
                return StatusCode(404);
            }

            visit.Status = Visit.StatusEnum.RepairedEnum;

            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(400);
            }

            return new ObjectResult(visit);
        }

        [HttpPut]
        [Route("/api/0.1.1/visits/{visitId}/pay")]
        [ValidateModelState]
        [SwaggerOperation("Diagnose")]
        public virtual IActionResult Pay([FromRoute][Required] int visitId)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }
            var visit = _context.Visits.FirstOrDefault(x => x.VisitId.Equals(visitId));
            if (visit is null)
                return StatusCode(404);
            // if (sender.Item1 != visit.CarOwnerUsername)
            //     return StatusCode(403);
            // if (visit.Status != Visit.StatusEnum.RepairedEnum)
            //     return StatusCode(403);
            visit.Status = Visit.StatusEnum.PaidEnum;
            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(400);
            }
            return StatusCode(200);
        }

        /// <summary>
        /// Update a visit
        /// </summary>

        /// <param name="body"></param>
        /// <response code="400">Validation exception</response>
        /// <response code="404">Visit not found</response>
        [HttpPut]
        [Route("/api/0.1.1/visits")]
        [ValidateModelState]
        [SwaggerOperation("UpdateVisit")]
        public virtual IActionResult UpdateVisit([FromBody] Visit body)
        {
            (string, UserType) sender;
            try
            {
                sender = Security.SolveGUID(_context, Request.Headers["Guid"]);
            }
            catch (Exception e)
            {
                return StatusCode(401, e.Message);
            }
            if (sender.Item2 != UserType.WORKSHOP_EMPLOYEE)
                return StatusCode(403);

            var visit = _context.Visits.FirstOrDefault(x => x.VisitId.Equals(body.VisitId));
            if (visit is null)
            {
                return StatusCode(404);
            }
            if (body.Date != null) visit.Date = body.Date;
            if (body.Price != null) visit.Price = body.Price;
            if (body.Priority != visit.Priority) visit.Priority = body.Priority;
            if (body.Type != visit.Type) visit.Type = body.Type;
            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateException)
            {
                return StatusCode(400);
            }

            return new ObjectResult(visit);
        }
    }
}